const fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('/tmp/ap40_embedded.js','utf8');
const store=new Map();
function el(){return {innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},click(){},scrollIntoView(){},value:'',files:[]}}
const els=new Map();
const document={getElementById(id){if(id==='main'||id==='toast'||id==='retryBtn'||id==='nav'||id==='micBtn'||id==='midiBtn'||id==='diagBtn'||id==='phaseName'||id==='daySide'||id==='phaseBar'||id==='buildVersion'||id==='diagOut') {if(!els.has(id))els.set(id,el());return els.get(id)} const main=els.get('main'); if(main && !main.innerHTML.includes('id=\"'+id+'\"') && !main.innerHTML.includes('id=\''+id+'\'')) return null; if(!els.has(id))els.set(id,el());return els.get(id)},querySelectorAll(){return []},querySelector(){return null},createElement(){return el()},body:el()};
const window={addEventListener(){},removeEventListener(){},setTimeout:(fn)=>{return 1},clearTimeout(){},scrollTo(){},requestAnimationFrame(){return 1},cancelAnimationFrame(){}};
window.window=window;
const context={setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,setInterval:()=>1,clearInterval:()=>{},window,document,navigator:{requestMIDIAccess:null,mediaDevices:null},location:{protocol:'file:'},localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},performance:{now:(()=>{let n=1000;return()=>n+=600})()},crypto:{randomUUID:()=>String(Date.now())},console,Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){},confirm:()=>true,alert:()=>{},structuredClone:undefined,Math,Date,JSON,Set,Map,Array,Object,Number,String,Boolean,RegExp,Error,parseInt,parseFloat,isFinite,isNaN,Intl,Promise};
vm.createContext(context);
try{vm.runInContext(src,context,{filename:'index.html.js'});}catch(e){console.error('LOAD_FAIL',e.stack);process.exit(1)}
const test=`
(async()=>{
 const R=[], ok=(n,d)=>R.push(['PASS',n,d||'']), bad=(n,e)=>R.push(['FAIL',n,String(e?.stack||e)]), A=(c,m)=>{if(!c)throw Error(m)}, midi=(pc,o=4)=>12*(o+1)+NOTE_NAMES.indexOf(pc), play=s=>s.forEach(n=>pressKey(n,'test'));
 try{state=normalizeState(clone(defaultState));state.day=1;state.lessons={};state.god.spaced.queue=[];for(const l of LESSONS){openLesson(l.id);switch(l.id){case'l1':play([48,60,72,84]);break;case'l2':play(['C','D','E','F','G','F','E','D','C'].map(midi));checkPattern('l2',patternExpected,'right');break;case'l3':rhythmTimes=[0,600,1200,1800];checkRhythm('l3');break;case'l4':play(['C','D','E','D','C'].map(midi));checkMemory();break;case'l5':earRound=[60,62,64];earInput=['C','D','E'];checkEar();completeEarAndContinue();break;case'l6':[['C',[60,64,67]],['G',[55,59,62]],['Am',[57,60,64]],['F',[53,57,60]]].forEach(x=>play(x[1]));checkChords('l6');break;case'l7':play(['C','G','A','F'].map(x=>midi(x,3)));checkPattern('l7',['C','G','A','F'],'left');break;case'l8':sepRightInput=['C','D','E','G'];sepLeftInput=['C','G','A','F'];checkSeparate('l8');break;case'l9':play(['C','D','E','G','E','D','C'].map(midi));checkPattern('l9',patternExpected,'memory2');break;case'l10':play(['C','D','E','G','E','D','C'].map(midi));rhythmTimes=[0,600,1200,1800,2400,3000,3600];checkRhythm2('l10');break;case'l11':chordSequence=['C','G','Am','F'];chordHits=new Set(['C','G','Am','F']);checkChords('l11');break;case'l12':autoInput=['C','D','E','G','E','D','C'];checkPattern('l12',patternExpected,'autonomy');break;default:if(l.kind==='chordgeneric'){chordSequence=l.targetChords.slice();checkGenericChords(l.id)}else{pattern=l.seq.slice();checkGeneric(l.id)}};A(state.lessons[l.id],l.id+' not completed')}A(state.day===90,'course ended at '+state.day);ok('90/90 curso');}catch(e){bad('90/90 curso',e)}
 try{state=normalizeState(clone(defaultState));state.day=3;state.lessons={l1:true,l2:true,l3:true};state.god.spaced.queue=[];show('spaced');seedSpaced();A(state.god.spaced.queue.length===3,'seed did not create 3');let x=state.god.spaced.queue[0];x.dueAt=new Date(Date.now()-86400000).toISOString();let idx=x.intervalIndex;spacedReview(x.id,true);A(x.intervalIndex===Math.min(5,idx+1),'success interval');x.dueAt=new Date(Date.now()-86400000).toISOString();spacedReview(x.id,false);A(x.intervalIndex===idx,'failure interval');ok('Repaso espaciado');}catch(e){bad('Repaso espaciado',e)}
 try{const vs=['home','course','practice','reading','rhythmReading','twoHands','phrases','technique','midiStudio','repertoire','ear','earAdvanced','accompaniment','progress','teacher','spaced','resources','settings'];for(const v of vs){show(v);A(document.getElementById('main').innerHTML.length>0,v+' empty')}ok('18 vistas');}catch(e){bad('18 vistas',e)}
 try{show('reading');readingExpectedSeq=[60];readingStage='play';readingPlayedSeq=[60];checkReading();ok('Lectura')}catch(e){bad('Lectura',e)}
 try{newRhythmReading();rhythmReadingArmed=true;rhythmReadingTimes=rhythmReadingPattern.beats.map((b,i)=>i?rhythmReadingPattern.beats.slice(0,i).reduce((a,x)=>a+x*600,0):0);checkRhythmReading();A(!rhythmReadingArmed,'rhythm reading open');ok('Lectura rítmica')}catch(e){bad('Lectura rítmica',e)}
 try{newTwoHands();startTwoHands();for(const ev of twoHandsPhrase.events)for(const n of ev.left.concat(ev.right))registerTwoHandsNote(n);checkTwoHands();A(twoHandsAwarded,'two hands');ok('Dos manos')}catch(e){bad('Dos manos',e)}
 try{newTechnique();startTechnique();const beat=60000/techniqueExercise.tempo;techniqueTimes=techniqueExercise.notes.map((_,i)=>i*beat);techniqueStep=techniqueExercise.notes.length;checkTechnique();A(techniqueAwarded,'technique');ok('Técnica')}catch(e){bad('Técnica',e)}
 try{newRepertoire();startRepertoire();repertoireInput=repertoirePiece.notes.slice();const unit=60000/repertoirePiece.tempo;repertoireTimes=repertoirePiece.notes.map((_,i)=>repertoirePiece.dur.slice(0,i).reduce((a,b)=>a+b*unit,0));checkRepertoire();A(repertoireAwarded,'repertoire');ok('Repertorio')}catch(e){bad('Repertorio',e)}
 try{state=normalizeState(clone(defaultState));startSightTest();prsInput=prsExpected.slice();const beat=60000/prsExcerpt.tempo;prsTimes=prsExpected.map((_,i)=>i*beat);finishSightTest();A(state.god.sight.attempts===1,'PRS');ok('PRS')}catch(e){bad('PRS',e)}
 try{state=normalizeState(clone(defaultState));midiTelemetry={notes:5,pedal:0,eventsOn:[0,1,2,3,4].map(i=>({note:60+i,velocity:80,time:i*500})),eventsOff:[0,1,2,3,4].map(i=>({note:60+i,duration:350}))};analyzePerformance();A(state.god.performance.sessions.length===1,'performance');ok('Performance')}catch(e){bad('Performance',e)}
 try{state=normalizeState(clone(defaultState));state.god.diagnostic={running:true,results:ENTRY_TASKS.map(t=>({id:t.id,score:80}))};finishEntryDiagnostic();A(state.god.diagnostic.score===80,'diagnostic');ok('Diagnóstico')}catch(e){bad('Diagnóstico',e)}
 try{state=normalizeState(clone(defaultState));show('ear');earRound=[60,62,64];earInput=['C','D','E'];checkEar();A(window._earSolved,'ear solved');completeEarAndContinue();A(state.lessons.l5,'ear complete');ok('Oído')}catch(e){bad('Oído',e)}
 try{state=normalizeState(clone(defaultState));show('accompaniment');accChordFeedback('C');ok('Acompañamiento')}catch(e){bad('Acompañamiento',e)}
 try{state=normalizeState(clone(defaultState));newPhrase();startPhrase();for(const ev of phrase.events)for(const n of ev.left.concat(ev.right))registerPhraseNote(n);const beat=60000/phrase.tempo;phraseTimes=phrase.events.map((_,i)=>i*beat);checkPhrase();A(phraseAwarded,'phrase');ok('Frases')}catch(e){bad('Frases',e)}
 try{state=normalizeState(clone(defaultState));state.god.practice.piece='rp1';state.god.practice.tempo=72;startSurgeryRound();for(const n of surgeryExpected)registerSurgeryNote(n);A(state.god.practice.rounds===1,'surgery round');ok('Modo cirugía')}catch(e){bad('Modo cirugía',e)}
 try{state=normalizeState(clone(defaultState));show('earAdvanced');for(const q of earAdvancedBank){earAdvancedState.question=q;earAdvancedState.started=true;if(q.type==='direction'){q.playNotes=[60,64];earAdvancedAnswer('Sube')}else if(q.type==='interval'){q.playNotes=[60,62];earAdvancedAnswer('Más cerca')}else if(q.type==='quality'){q.playNotes=[60,64,67];earAdvancedAnswer('Mayor')}else if(q.type==='chord'){q.playNotes=[60,64,67];earAdvancedAnswer('Tónica')}else if(q.type==='progression'){q.playNotes=[60,67,69,65];earAdvancedAnswer('I-V-vi-IV')}else if(q.type==='memory'){q.playNotes=[60,62,64,62];earAdvancedState.answer=q.playNotes.slice();earAdvancedCheckKeyboard()}else if(q.type==='tonic'){q.playNotes=[60,64,67,64,60];earAdvancedState.answer=[60];earAdvancedCheckKeyboard()}else if(q.type==='transcribe'){q.playNotes=[60,62,64,67,64];earAdvancedState.answer=q.playNotes.slice();earAdvancedCheckKeyboard()}}A(state.earAdvanced.total===8,'advanced ear');ok('Oído avanzado','8 tipos de prueba evaluados')}catch(e){bad('Oído avanzado',e)}
 console.log(R.map(x=>x[0]+' '+x[1]+(x[2]?' :: '+x[2]:'')).join('\\n'));console.log('TOTAL '+R.length+' PASS '+R.filter(x=>x[0]==='PASS').length+' FAIL '+R.filter(x=>x[0]==='FAIL').length);
})()`;
vm.runInContext(test,context,{filename:'tests.js'});
